volumes:
  product-data:
    external: true
services:
  frontend:
    command: /bin/bash run.sh
    environment:
      HOST: 0.0.0.0
      NODE_ENV: ${NODE_ENV}
    image: node:lts-bullseye
    ports:
    - 5173:5173
    volumes:
    - ./frontend:/app
    working_dir: /app
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: /bin/bash start.sh
    environment:
      NODE_ENV: ${NODE_ENV}
      PRICE_CHARTING_KEY: ${PRICE_CHARTING_KEY}
      MONGOHOST: ${MONGOHOST}
      MONGODATABASE: ${MONGODATABASE}
      MONGOUSER: ${MONGOUSER}
      MONGOPASSWORD: ${MONGOPASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  mongo:
    image: mongo:6-jammy
    volumes:
      - product-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOPASSWORD}
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'productdata'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'productdata'
      ME_CONFIG_MONGODB_URL: mongodb://productdata:productdata@mongo:27017/
    restart: always


